controllers:
    resource: routing.controllers

api_common:
    prefix: /api/v1
    resource:
        path: ../src/Common/Controller/
        namespace: App\Common\Controller
    type: attribute

api_trade:
    prefix: /api/v1
    resource:
        path: ../src/Trade/Controller/
        namespace: App\Trade\Controller
    type: attribute

api_wallet:
    prefix: /api/v1
    resource:
        path: ../src/Wallet/Controller/
        namespace: App\Wallet\Controller
    type: attribute

api_payment_app:
    prefix: /api/v1
    resource:
        path: ../src/Payment/Controller/App/
        namespace: App\Payment\Controller\App
    type: attribute

api_payment_manage:
    prefix: /api/v1
    resource:
        path: ../src/Payment/Controller/Manage/
        namespace: App\Payment\Controller\Manage
    type: attribute

payment_webhook:
    resource:
        path: ../src/Payment/Controller/Webhook/
        namespace: App\Payment\Controller\Webhook
    type: attribute

wechat:
    resource:
        path: ../src/Wechat/Controller/
        namespace: App\Wechat\Controller
    type: attribute

wechat_app:
    prefix: /api/v1
    resource:
        path: ../src/Wechat/Controller/App/
        namespace: App\Wechat\Controller\App
    type: attribute
