controllers:
    resource: routing.controllers

api_common:
    prefix: /api/v1
    resource:
        path: ../src/Common/Controller/
        namespace: App\Common\Controller
    type: attribute

api_trade:
    prefix: /api/v1
    resource:
        path: ../src/Trade/Controller/
        namespace: App\Trade\Controller
    type: attribute

api_wallet:
    prefix: /api/v1
    resource:
        path: ../src/Wallet/Controller/
        namespace: App\Wallet\Controller
    type: attribute
