# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

parameters: {}

imports:
    - { resource: '../src/Core/Resources/config/services.yaml', ignore_errors: true }
    - { resource: '../src/Identity/Resources/config/services_identity.yaml', ignore_errors: true }
    - { resource: '../src/Payment/Resources/config/services_payment.yaml', ignore_errors: true }
    - { resource: '../src/Wechat/Resources/config/services_wechat.yaml', ignore_errors: true }

services:
    _defaults:
        autowire: true
        autoconfigure: true

    _instanceof:
        App\Core\Controller\RestController:
            calls:
                - [ setRequestStack, [ '@request_stack' ] ]
                - [ setSerializer, [ '@serializer' ] ]
                - [ setTranslator, [ '@translator' ] ]
        App\Payment\Service\PaymentGatewayInterface:
            tags: ['payment.gateway']
        App\Payment\Service\Adjustment\PaymentAdjustmentProviderInterface:
            tags: ['payment.adjustment_provider']

    App\:
        resource: '../src/'
        exclude:
            - '../src/Core/Serializer/Normalizer/FlatNormalizer.php'
            - '../src/Core/EventListener/*'
            - '../src/Identity/Controller/AuthController.php'
            - '../src/Identity/Controller/OtpController.php'
            - '../src/Identity/Security/TokenManager.php'
            - '../src/Identity/Sms/AliyunSmsProvider.php'
            - '../src/Identity/Service/RedisOtpStorage.php'
            - '../src/Wechat/Service/WechatService.php'
            - '../src/Wechat/Service/Gateway/WechatPayGateway.php'

    App\Core\EventListener\OpenApiEnricherListener:
        tags:
            - { name: kernel.event_listener, event: kernel.response, priority: -10 }

    Symfony\Component\DependencyInjection\ContainerInterface: '@service_container'
    Psr\Log\LoggerInterface: '@logger'
    Symfony\Component\Serializer\SerializerInterface: '@serializer'
    Symfony\Contracts\Translation\TranslatorInterface: '@translator'
    App\Core\Service\ServiceLocatorInterface: '@App\Core\Service\DefaultServiceLocator'

    App\Identity\Service\OtpStorageInterface: '@App\Identity\Service\LocalCacheOtpStorage'

    App\Identity\Service\LocalCacheOtpStorage:
        arguments:
            $cache: '@cache.app'

    App\Identity\Service\OtpService:
        arguments:
            $storage: '@App\Identity\Service\LocalCacheOtpStorage'
            $sms: '@App\Identity\Sms\AliyunSmsProvider'

when@test:
    services:
        App\Identity\Service\OtpStorageInterface: '@App\Identity\Service\NullOtpStorage'
        App\Identity\Service\RedisOtpStorage: null
        App\Identity\Service\OtpService:
            arguments:
                $storage: '@App\Identity\Service\NullOtpStorage'
                $sms: '@App\Identity\Sms\AliyunSmsProvider'
